<?php
// $Id$
/*
 * Converted to Drupal 4.7 by Waldemar Schlackow
 */

include_once('ldap_integration/conf.php');
include_once('ldap_integration/LDAPInterface.php');

/*
 * Private constants. Do not touch
 */
define(LDAP_PERM_SEARCH, 'perform ldap searches');
define(LDAP_SETTINGS_GROUP_STRING, 'LDAP attributes');
define(LDAP_USER_DATA_EDIT_TAB, 'LDAP entry');
define(LDAP_CATEGORY_USER_DATA, 'ldap_user_data');

define(LDAP_STANDARD_SYSTEM, 0);
define(LDAP_AD_SYSTEM, 1);

define(LDAP_FIRST_DRUPAL, 0);
define(LDAP_FIRST_LDAP, 1);

define(LDAP_MAP_ATTRIBUTES, 0);
define(LDAP_MAP_ONLY_LOST_PASSWORDS, 1);
define(LDAP_MAP_NOTHING, 2);

define(LDAP_GROUP_IN_DN, 'ldap_group_in_dn');
define(LDAP_GROUP_IN_ATTR, 'ldap_group_in_attr');
define(LDAP_GROUP_AS_ENTRIES, 'ldap_group_as_entries');

/*
 * Private constants (default values). Do not touch either
 */
define(LDAP_DEFAULT_ORG, 'Home');
define(LDAP_DEFAULT_PATTERN, '/(\S+)@(\S+)\.(\S+)/i');
define(LDAP_DEFAULT_REPLACEMENT, 'cn=$1,dc=$2,dc=$3');
define(LDAP_DEFAULT_BASE_DN, 'ou=Users,dc=drupal,dc=org');
define(LDAP_DEFAULT_GROUP_DN_PATTERN, '/cn=\S+,ou=(\S+),dc=\S+,dc=\S+/i');
define(LDAP_DEFAULT_GROUP_ATTR, 'userGroups');
define(LDAP_DEFAULT_GROUP_ENTRIES, 'cn=Group,dc=example,dc=com');
define(LDAP_DEFAULT_GROUP_ENTRIES_ATTRIBUTE, 'memberUid');

$GLOBALS['ldap'] = new LDAPInterface();
$GLOBALS['ldap']->setServer(variable_get('ldap_server', 'localhost'));
$GLOBALS['ldap']->setPort(variable_get('ldap_port', 389));
$GLOBALS['ldap']->setOption('TLS', variable_get('ldap_use_TLS', false));


/*********************************
 *       1. Drupal hooks         *
 *********************************/

function ldap_integration_help($section) {
  $output = '';

  switch ($section) {
    case 'admin/modules#ldap_integration':
      $output = 'ldap_integration';
      break;
    case 'admin/modules#description':
    case 'admin/help#ldap_integration':
      $output = t('Enables authentication via LDAP.');
      break;
    case 'user/help#ldap_integration':
      $output = t('<p>If you are registered in %org LDAP directory, you\'ll probably be able to login this site by using your LDAP login and password</p>', array('%org' => variable_get('ldap_org_name', '')));
      break;
  }

  return $output;
}

function ldap_integration_settings($section = 'server') {
  // Reminding admins about conf.php
  $form['ldap_message'] = array(
    '#value' => '<p><strong style="color: red;">PLEASE NOTE</strong>: do not forget there are further and important settings to be set in the module\'s config file, located at <code>modules/ldap_integration/conf.php</code> in your Drupal install.</p>',
  );

  // Server settings

  $form['ldap_org_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Organisation name'),
    '#default_value' => variable_get('ldap_org_name', ''),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Name of the organisation the LDAP directory belongs to.'),
  );
  $form['ldap_server'] = array(
    '#type' => 'textfield',
    '#title' => t('LDAP server'),
    '#default_value' => variable_get('ldap_server', 'localhost'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('The domain name or IP address of your LDAP Server.'),
  );
  $form['ldap_port'] = array(
    '#type' => 'textfield',
    '#title' => t('LDAP port'),
    '#default_value' => variable_get('ldap_port', 389),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('The TCP/IP port on the above server which accepts LDAP connections. Must be an integer.'),
  );
  $form['ldap_use_TLS'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use TLS encryption'),
    '#return_value' => 1,
    '#default_value' => variable_get('ldap_use_TLS', 0),
    '#description' => t('Secure the connection between the Drupal and the LDAP servers using TLS.'),
  );
  $form['ldap_store_encrypted_pass'] = array(
    '#type' => 'checkbox',
    '#title' => t('Store passwords in encrypted form'),
    '#return_value' => 1,
    '#default_value' => variable_get('ldap_store_encrypted_pass', 0),
    '#description' => t('Secure the password in LDAP by storing it MD5 encrypted (use with care, as some LDAP directories may do this automatically, what would cause logins problems).'),
  );

  return $form;
}

function ldap_integration_settings_login_procedure() {

  $form['ldap_message'] = array(
    '#value' => '<p>' . t('Here you can specify the details of the login procedure') . '</p>',
  );

  // Login process
  $options_login_process = array(
      LDAP_FIRST_DRUPAL => t('Drupal\'s own database. If it fails, will look on the LDAP directory'),
      LDAP_FIRST_LDAP => t('LDAP directory only'));

  $form['ldap_login_process'] = array(
    '#type' => 'radios',
    '#title' => t('When logging in, Drupal will look up for the user on'),
    '#default_value' => variable_get('ldap_login_process', LDAP_FIRST_DRUPAL),
    '#options' => $options_login_process,
    '#description' => NULL,
    '#required' => true,
  );

  $form['ldap_attr_mapping'] = array(
    '#type' => 'radios',
    '#title' => t('Should Drupal account fields be mapped to LDAP attributes?'),
    '#default_value' => variable_get('ldap_attr_mapping', LDAP_MAP_NOTHING),
    '#options' => $options_attribute_mapping,
    '#description' => NULL,
    '#required' => true,
  );

  // System type and user mapping
  $form['ldap_system_type_1']['ldap_system_type'] = array(
    '#type' => 'radio',
    '#name' => 'edit[ldap_system_type]',
    '#title' => t('Standard LDAP system'),
    '#default_value'=> (variable_get('ldap_system_type', LDAP_STANDARD_SYSTEM) == LDAP_STANDARD_SYSTEM),
    '#return_value' => LDAP_STANDARD_SYSTEM,
    '#prefix' => '<dl><dt>',
    '#suffix' => '</dt>'
  );

  $form['ldap_login_pattern'] = array(
    '#type' => 'textfield',
    '#title' => t('LDAP login pattern'),
    '#default_value' => variable_get('ldap_login_pattern', LDAP_DEFAULT_PATTERN),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Regular expression matching logins for this module, that will be in the form of an e-mail address. <em>Example: %s </em>.', array('%s' => LDAP_DEFAULT_PATTERN)),
    '#prefix' => '<dd>',
    '#suffix' => '</dd>'
  );

  $form['ldap_login_replacement'] = array(
    '#type' => 'textfield',
    '#title' => t('LDAP login replacement'),
    '#default_value' => variable_get('ldap_login_replacement', LDAP_DEFAULT_REPLACEMENT),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Replacement to convert the above regular expression into the user\'s LDAP DN. <em>Example: %s</em>.', array('%s' => LDAP_DEFAULT_REPLACEMENT)),
    '#prefix' => '<dd>',
    '#suffix' => '</dd>'
  );

  $form['ldap_system_type_2']['ldap_system_type'] = array(
    '#type' => 'radio',
    '#name' => 'edit[ldap_system_type]',
    '#title' => t('eDirectory or Active Directory system'),
    '#default_value'=> (variable_get('ldap_system_type', LDAP_STANDARD_SYSTEM) == LDAP_AD_SYSTEM),
    '#return_value' => LDAP_AD_SYSTEM,
    '#prefix' => '<dt>',
    '#suffix' => '</dt>'
  );

  $form['ldap_base_dn'] = array(
    '#type' => 'textarea',
    '#title' => t('Base DNs'),
    '#default_value' => variable_get('ldap_base_dn', LDAP_DEFAULT_BASE_DN),
    '#cols' => 50,
    '#rows' => 6,
    '#description' => t('Base DN for users, to be used in eDirectory or Active Directory logins'),
    '#prefix' => '<dd>',
    '#suffix' => '</dd>'
  );

  $form['ldap_user_attribute'] = array(
    '#type' => 'textfield',
    '#title' => t('UserName attribute'),
    '#default_value' => variable_get('ldap_user_attribute', 'sAMAccountName'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('The attribute that holds the Users Loginname. (eg. <em>cn</em> for eDir or <em>sAMAccountName</em> for AD)'),
    '#prefix' => '<dd>',
    '#suffix' => '</dd></dl>'
  );

  return system_settings_form('ldap_integration_settings_login_procedure', $form);
}

function ldap_integration_settings_groups() {
  $form['ldap_message'] = array(
    '#value' => '<p>' . t('You may want your users to attain Drupal roles according to their LDAP groups. If that is the case, this is the place to tell the module how.') . '</p>',
  );

  // LDAP groups <-> Drupal roles
  $form['ldap_groups_in_dn'] = array(
    '#type' => 'checkbox',
    '#title' => t('Group is specified in user\'s DN'),
    '#default_value' => variable_get('ldap_groups_in_dn', false),
    '#prefix' => '<dl><dt>',
    '#suffix' => '</dt>'
  );

  $form['ldap_group_dn_pattern'] = array(
    '#type' => 'textfield',
    '#title' => t('Regular expression representing the pattern'),
    '#default_value' => variable_get('ldap_group_dn_pattern', LDAP_DEFAULT_GROUP_DN_PATTERN),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Regular expression matching users\' DNs. Each <strong>parenthesized</strong> subexpression points out a group name. <em>Example: ' . LDAP_DEFAULT_GROUP_DN_PATTERN . '. In this example, \'ou=\' is followed by a group name that Drupal will associate to a role name</em>.'),
    '#prefix' => '<dd>',
    '#suffix' => '</dd>'
  );

  $form['ldap_groups_in_attr'] = array(
    '#type' => 'checkbox',
    '#title' => t('Groups are specified by LDAP attributes'),
    '#default_value' => variable_get('ldap_groups_in_attr', false),
    '#prefix' => '<dt>',
    '#suffix' => '</dt>'
  );

  $form['ldap_group_attr'] = array(
    '#type' => 'textarea',
    '#title' => t('Attribute names (one per line)'),
    '#default_value' => variable_get('ldap_group_attr', LDAP_DEFAULT_GROUP_ATTR),
    '#cols' => 50,
    '#rows' => 6,
    '#description' => t('Name of the LDAP attributes containing the group names for each user.'),
    '#prefix' => '<dd>',
    '#suffix' => '</dd>'
  );

  $form['ldap_groups_as_entries'] = array(
    '#type' => 'checkbox',
    '#title' => t('Groups exist as LDAP entries where a multivalued attribute contains the members\' CNs'),
    '#default_value' => variable_get('ldap_groups_as_entries', false),
    '#prefix' => '<dt>',
    '#suffix' => '</dt>'
  );

  $form['ldap_group_entries'] = array(
    '#type' => 'textarea',
    '#title' => t('Entries containing groups (one per line)'),
    '#default_value' => variable_get('ldap_group_entries', LDAP_DEFAULT_GROUP_ENTRIES),
    '#cols' => 50,
    '#rows' => 6,
    '#description' => t('Name of the LDAP entries representing user groups.'),
    '#prefix' => '<dd>',
    '#suffix' => '</dd>'
  );

  $form['ldap_group_entries_attribute'] = array(
    '#type' => 'textfield',
    '#title' => t('Attribute holding group members'),
    '#default_value' => variable_get('ldap_group_entries_attribute', LDAP_DEFAULT_GROUP_ENTRIES_ATTRIBUTE),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Name of the multivalued attribute which holds the CNs of group members, for example: <em>' . LDAP_DEFAULT_GROUP_ENTRIES_ATTRIBUTE . '</em>.'),
    '#prefix' => '<dd>',
    '#suffix' => '</dd></dl>'
  );

  $options_grouproles = array(
    LDAP_GROUP_IN_DN => array('choice' => t('Group is specified in user\'s DN'), 'extended' => $option_grouproles_1),
    LDAP_GROUP_IN_ATTR => array('choice' => t('Groups are specified by LDAP attributes'), 'extended' => $option_grouproles_2),
    LDAP_GROUP_AS_ENTRIES => array('choice' => t('Groups exist as LDAP entries where a multivalued attribute contains the members\' CNs'), 'extended' => $option_grouproles_3));

  $form['ldap_map_group_signoffs'] = array(
    '#type' => 'checkbox',
    '#title' => t('Map group sign offs'),
    '#return_value' => true,
    '#default_value' => variable_get('ldap_map_group_signoffs', true),
    '#description' => t('If you enable this, users signed off LDAP groups will be denied the respective Drupal roles, according to the rules set on <code>modules/ldap_integration/conf.php</code>.'),
  );

  return system_settings_form('ldap_integration_settings_groups', $form);
}

function ldap_integration_settings_attributes() {
  // LDAP attributes viewing/editing
  global $ldap_attributes;

  // Explanatory text
  $form['ldap_message'] = array(
    '#value' => '<p>' . t('Users may be able to view their LDAP attributes\' values, as well as edit them. You can configure this feature here.') . '</p>',
  );

  foreach ($ldap_attributes as $key => $field) {
    $fields[$key] = $field[2];
  }

  $form['ldap_user_attributes'] = array(
    '#type' => 'select',
    '#title' => t('Attributes displayed on user pages'),
    '#default_value' => variable_get('ldap_user_attributes', array()),
    '#options' => $fields,
    '#description' => t('Select the attributes which will be displayed on user pages. Blank attributes will be omitted. You may add attributes to this list by editing the relevant global variable at the beginning of the module\'s code'),
    '#attributes' => array('size'=> "6"),
    '#multiple' => true,
    '#required' => false,
  );  
  $form['ldap_useredit_attributes'] = array(
    '#type' => 'select',
    '#title' => t('Attributes that can be edited by users'),
    '#default_value' => variable_get('ldap_useredit_attributes', array()),
    '#options' => $fields,
    '#description' => t('Select the attributes users will be able to edit on their user pages. Blank attributes will be omitted. You may add attributes to this list by editing the relevant global variable at the beginning of the module\'s code'),
    '#attributes' => array('size'=> "6"),
    '#multiple' => true,
    '#required' => false,
  );

  return system_settings_form('ldap_integration_settings_attributes', $form);
}

function ldap_integration_auth($name, $pass, $server) {
  global $ldap;

  $ret = false;

  if(variable_get('ldap_system_type', LDAP_STANDARD_SYSTEM) == LDAP_STANDARD_SYSTEM) {
    $dn = _ldap_integration_login2dn($server ? "$name@$server" : $name);
    $ret = $ldap->connect($dn, $pass);
  }
  else {
    $possible_base_dns = explode("\r\n", variable_get('ldap_base_dn', ''));
    foreach ($possible_base_dns as $base_dn) {
      if($base_dn && $ret = $ldap->connect_ADstyle(variable_get('ldap_user_attribute', ''), $name, $base_dn, $pass)) {
          break;
      }
    }
  }

  return $ret;
}

function ldap_integration_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/settings/ldap_integration/server',
      'title' => t('LDAP server settings'),
      'callback' => 'system_site_settings',
      'callback_arguments' => array('ldap_integration'),
      'weight' => 0,
      'type' => MENU_DEFAULT_LOCAL_TASK);
    $items[] = array(
      'path' => 'admin/settings/ldap_integration/login_procedure',
      'title' => t('Login procedure'),
      'callback' => 'ldap_integration_settings_login_procedure',
      'weight' => 1,
      'type' => MENU_LOCAL_TASK);
    $items[] = array(
      'path' => 'admin/settings/ldap_integration/groups',
      'title' => t('Groups and roles'),
      'callback' => 'ldap_integration_settings_groups',
      'weight' => 2,
      'type' => MENU_LOCAL_TASK);
    $items[] = array(
      'path' => 'admin/settings/ldap_integration/attributes',
      'title' => t('LDAP attributes'),
      'callback' => 'ldap_integration_settings_attributes',
      'weight' => 3,
      'type' => MENU_LOCAL_TASK);
  }
  return $items;
}

function ldap_integration_user($op, &$edit, &$user, $category = NULL) {
  switch($op) {
    case 'categories':
      return ldap_integration_user_categories();
    case 'form':
      return ldap_integration_user_form($user, $category);
    case 'load':
      ldap_integration_user_load($user);
      break;
    case 'login':
      ldap_integration_user_login($user);
      break;
    case 'update':
      ldap_integration_user_update($edit, $user, $category);
      break;
    case 'view':
      return ldap_integration_user_view($user);
  }
}

function ldap_integration_form_alter($form_id, &$form) {
  if ($form_id == 'user_login_block') {
    $form['#validate'] = array('ldap_integration_login_validate' => array());
  }
}


/*********************************
 *     2. Delegate functions     *
 *********************************/

function ldap_integration_user_categories() {
  global $user;

  $ret = null;

  if ($user->ldap_authentified && variable_get('ldap_useredit_attributes', array())) {
    $ret = array(array('name' => LDAP_CATEGORY_USER_DATA, 'title' => t(LDAP_USER_DATA_EDIT_TAB), 'weight' => 10));
  }

  return $ret;
}

function ldap_integration_user_form($user, $category) {
  global $ldap_attributes, $ldap;

  if (!$user->ldap_authentified || $category != LDAP_CATEGORY_USER_DATA || ! $attributes = variable_get('ldap_useredit_attributes', array())) {
    return;
  }

  $ldap->disconnect();
  if (!$ldap->connect(LDAP_READER_USER_DN, LDAP_READER_USER_PASS)) {
    watchdog('user', "User load: user $user->name's data could not be read in the LDAP directory");
    return;
  }

  $entry = $ldap->retrieveAttributes($user->ldap_dn);

  $output = '';
  $form['ldap_attributes'] = array(
    '#type' => 'fieldset',
    '#title' => t('LDAP Attributes')
  );

  foreach($attributes as $attribute) {
    $attr_info = $ldap_attributes[$attribute];
    if ($attr_info) {
      array_shift($attr_info);
      $value = $entry[strtolower($attribute)][0];
      $form['ldap_attributes'][$attribute] = _ldap_integration_attribute_form($attribute, $value, $attr_info);
    }
  }

  $ldap->disconnect();

  return $form;
}

function ldap_integration_user_load(&$user) {
  global $ldap, $ldap_drupal_mappings;

  if (!$user->ldap_authentified || !variable_get('ldap_attr_mapping', LDAP_MAP_ATTRIBUTES) == LDAP_MAP_ATTRIBUTES) {
    return;
  }

  if (!$ldap->connect(LDAP_READER_USER_DN, LDAP_READER_USER_PASS)) {
    watchdog('user', "User load: user $user->name's data could not be read in the LDAP directory");
    return;
  }

  $newuser = $user;
  foreach ($ldap_drupal_mappings as $ldap_attr => $drupal_field) {
    if ($drupal_field != 'pass') {
      $newuser->$drupal_field = $ldap->retrieveAttribute($user->ldap_dn, $ldap_attr);
    } else {
      $cleartext_pass = $ldap->retrieveAttribute($user->ldap_dn, $ldap_attr);
    }
  }

  if ($newuser != $user) {
    $newuser->pass = $cleartext_pass; // Drupal will do the md5 hash
    $user = user_save($user, get_object_vars($newuser));
  }

  $ldap->disconnect();
}

function ldap_integration_user_login(&$user) {
  global $ldap, $ldap_group_role_mappings;

  // Mapping LDAP groups to Drupal roles
  if (!$user->ldap_authentified) {
    return;
  }

  if (!$ldap->connect(LDAP_READER_USER_DN, LDAP_READER_USER_PASS)) {
    watchdog('user', "User login: user $user->name's data could not be read in the LDAP directory");
    return;
  }

  if (variable_get('ldap_map_group_signoffs', false)) {
    // First, we take every mapped role from the user, later below
    // we'll grant back those deserved.
    foreach ($ldap_group_role_mappings as $role) {
      _ldap_integration_take_role_from_user($user, $role);
    }
  }

  $groups_in_dn = variable_get('ldap_groups_in_dn', false);
  $groups_in_attr = variable_get('ldap_groups_in_attr', false);
  $groups_as_entries = variable_get('ldap_groups_as_entries', false);
  $dn_groups = array(); 
  if ($groups_in_dn && $dn_groups_regexp = variable_get('ldap_group_dn_pattern', '')) {
    preg_match($dn_groups_regexp, $user->ldap_dn, $matches);
    $dn_groups = array_slice($matches, 1);
  }

  $attrib_groups = array();
  if ($groups_in_attr && $attributes = variable_get('ldap_group_attr', '')) {
    $attributes_array = explode("\r\n", $attributes);
    foreach ($attributes_array as $attribute) {
      $tmp = $ldap->retrieveMultiAttribute($user->ldap_dn, $attribute);
      $attrib_groups = array_merge($attrib_groups, $tmp);
    }
  }

  $entries_groups = array();
  if ($groups_as_entries && $entries = variable_get('ldap_group_entries', '')) {
    $entries_array = explode("\r\n", $entries);
    foreach ($entries_array as $entry) {
      $tmp = $ldap->retrieveMultiAttribute($entry, variable_get('ldap_group_entries_attribute', LDAP_DEFAULT_GROUP_ENTRIES_ATTRIBUTE));
      if (in_array($user->name, $tmp)) {
        $entries_groups[] = $entry;
      }
    }
  }

  $groups = array_merge($dn_groups, $attrib_groups, $entries_groups);

  foreach ($groups as $key => $group) {
    if ($role = $ldap_group_role_mappings[$group]) {
      _ldap_integration_create_role($role);
      _ldap_integration_give_role_to_user($user, $role);
    }
  }
  $ldap->disconnect();
}

function ldap_integration_user_update(&$edit, $user, $category) {
  global $ldap;

  if (!$user->ldap_authentified) {
    return;
  }

  // Three cases here:
  //   1. User logged on and editing his LDAP entry attributes ($category == LDAP_CATEGORY_USER_DATA).
  //   2. User logged on and editing his Drupal account settings ($category == 'account').
  //   3. Password lost and being updated (category == 'account').

  // So, case 1
  if ($category == LDAP_CATEGORY_USER_DATA && variable_get('ldap_useredit_attributes', array())) {
    ldap_integration_user_update_ldap_attributes($edit, $user);
  }
  // Cases 2 && 3
  else if ($category == 'account') {
    ldap_integration_user_update_drupal_account($edit, $user);
  }
}

function ldap_integration_user_update_ldap_attributes(&$edit, $user) {
  global $ldap;

  $ldap->disconnect();
  if(!$ldap->connect(LDAP_WRITER_USER_DN, LDAP_WRITER_USER_PASS)) {
    watchdog('user', "User update: user $user->name's data could not be updated in the LDAP directory");
    return;
  }

  $writeout = array();
  $editables = variable_get('ldap_useredit_attributes', array());

  foreach ($edit as $edit_attr => $edit_val) {
    // Preventing a POST data injection: we check allowance to write value.
    if (array_search($edit_attr, $editables) !== FALSE) {
      $writeout[$edit_attr] = $edit_val;
      $edit[$edit_attr] = null;
    }
  }

  if ($writeout) {
    $ldap->writeAttributes($user->ldap_dn, $writeout);
  }

  $ldap->disconnect();
}

function ldap_integration_user_update_drupal_account(&$edit, $user) {
  global $ldap, $ldap_drupal_mappings;

  $ldap->disconnect();
  if(!$ldap->connect(LDAP_WRITER_USER_DN, LDAP_WRITER_USER_PASS)) {
    watchdog('user', "User update: user $user->name's data could not be updated in the LDAP directory");
    return;
  }

  $password_updated_in_ldap =
       variable_get('ldap_attr_mapping', LDAP_MAP_NOTHING) == LDAP_MAP_ONLY_LOST_PASSWORDS
    || variable_get('ldap_attr_mapping', LDAP_MAP_NOTHING) == LDAP_MAP_ATTRIBUTES;

  $account_updated_in_ldap = (variable_get('ldap_attr_mapping', LDAP_MAP_NOTHING) == LDAP_MAP_ATTRIBUTES);

  if ($edit['pass'] && sizeof($edit) == 1 && $password_updated_in_ldap) {
    // Case 3: password lost and new one generated randomly => update LDAP password
    $drupal2ldap_mappings = array_flip($ldap_drupal_mappings);
    $pass_ldap_attribute = $drupal2ldap_mappings['pass'];
    $pw = variable_get('ldap_store_encrypted_pass', false) ? '{md5}' . base64_encode(pack('H*', md5($edit['pass']))) : $edit['pass'];
    $ldap->writeAttributes($user->ldap_dn, array($pass_ldap_attribute => $pw));
  }
  else if ($edit['pass'] && sizeof($edit) == 1 && !$password_updated_in_ldap) {
    //   Same, but NOT having permission to update passwords
    drupal_set_message('Lost passwords recovery has been disabled for LDAP users. Please contact your system administrator in order to get a new password.');
    //   Nulling out this field should suffice for Drupal not to try
    // to regenerate the password, but it doesn't, so I add a drupal_goto()
    $edit['pass'] = null; 
    drupal_goto('user/login');
  }
  else if ($user->ldap_authentified && $account_updated_in_ldap) {
    // Case 2: updating account data
    $drupal2ldap_mappings = array_flip($ldap_drupal_mappings);
    $writeout = array();
    foreach ($edit as $key => $value) {
      $ldap_attr = $drupal2ldap_mappings[$key];
      // $writeout[$ldap_attr] = $value;
      if ($ldap_attr) {
        if ($key == 'pass') {
          $pw = variable_get('ldap_store_encrypted_pass', false) ? '{md5}' . base64_encode(pack('H*', md5($value))) : $value;
          $writeout[$ldap_attr] = $pw;
        } else {
          $writeout[$ldap_attr] = $value;
        }
      }
    }
    $ldap->writeAttributes($user->ldap_dn, $writeout);
  }

  $ldap->disconnect();
}

function ldap_integration_user_view($user) {
  global $ldap;

  if (!$user->ldap_authentified) {
    return;
  }

  $ldap->disconnect();
  
  if (!$ldap->connect(LDAP_READER_USER_DN, LDAP_READER_USER_PASS)) {
    watchdog('user', "User load: user $user->name's data could not be read in the LDAP directory");
    return;
  }

  if ($user->uid == arg(1)){ //for admins, who might otherwise see their ldap info while viewing other accounts
	  $entry = $ldap->retrieveAttributes($user->ldap_dn);
	
	  $ret = array();
	  $allowed_attrs = variable_get('ldap_user_attributes', array()) ? variable_get('ldap_user_attributes', array()) : array();
	
	  foreach($allowed_attrs as $attribute) {
		$shown_attrs[$attribute] = $entry[strtolower($attribute)][0];
	  }
	
	  $ret[LDAP_SETTINGS_GROUP_STRING][] = theme('ldap_integration_ldap_entry', $shown_attrs);
	
	  // Disconnecting just in case, for the sake of security  
	  $ldap->disconnect();
	  }
  return $ret;
}


/*********************************
 *    3. Auxiliary functions     *
 *********************************/

// Patched (2005-09-06) by sfrancis@drupal.org
function _ldap_integration_login2dn($login) {
  global $ldap;

  if(variable_get('ldap_system_type', LDAP_STANDARD_SYSTEM) == LDAP_STANDARD_SYSTEM) {
    $string = $login;
    $pattern = variable_get('ldap_login_pattern', LDAP_DEFAULT_PATTERN);
    $replacement = variable_get('ldap_login_replacement', LDAP_DEFAULT_REPLACEMENT);
    $ret = preg_replace($pattern, $replacement, $string);
  } else {
    $possible_base_dns = explode("\r\n", variable_get('ldap_base_dn',''));
    foreach ($possible_base_dns as $dn) {
      if ($ret = $ldap->name_to_dn_AD(variable_get('ldap_user_attribute', ''), $login, $dn)) {
        break;
      }
    }
  }

  return $ret;
}

function _ldap_integration_attribute_form($attrname, $value, $info) {
  $type = array_shift($info);

  switch($type) {
    case 'textfield':
      $form = array(
        '#type' => 'textfield',
        '#title' => array_shift($info),
        '#default_value' => $value,
        '#size' => array_shift($info),
        '#maxlength' => array_shift($info),
        '#description' => array_shift($info),
        '#attributes' => array_shift($info),
        '#required' => array_shift($info),
      );
      break;
    case 'password':
      $form = array(
        '#type' => 'password',
        '#title' => array_shift($info),
        '#default_value' => $value,
        '#size' => array_shift($info),
        '#maxlength' => array_shift($info),
        '#description' => array_shift($info),
      );
      break;
  }

  return $form;
}

function _ldap_integration_give_role_to_user($user, $rolename) {
  $result = db_query("SELECT * FROM {role} WHERE name = '$rolename'");
  $role_exists = db_num_rows($result);

  if ($role_exists) {
    $role = db_fetch_object($result);
    $result = db_query("SELECT * FROM {users_roles} WHERE uid = $user->uid AND rid = $role->rid");
    $role_already_given = db_num_rows($result);
    if (!$role_already_given) {
     db_query("INSERT {users_roles} SET uid = $user->uid, rid = $role->rid");
    }
  }
}

function _ldap_integration_take_role_from_user($user, $rolename) {
  $result = db_query("SELECT * FROM {role} WHERE name = '$rolename'");
  $role_exists = db_num_rows($result);

  if ($role_exists) {
    $role = db_fetch_object($result);
    $result = db_query("SELECT * FROM {users_roles} WHERE uid = $user->uid AND rid = $role->rid");
    $role_present = db_num_rows($result);
    if ($role_present) {
      db_query("DELETE FROM {users_roles} WHERE uid = $user->uid AND rid = $role->rid");
    }
  }
}

function _ldap_integration_create_role($rolename) {
  $result = db_query("SELECT * FROM {role} WHERE name = '$rolename'");
  $role_exists = db_num_rows($result);

  if (!$role_exists) {
     db_query("INSERT {role} SET name = '$rolename'");
  }
}


/*********************************
 *    4. Login process hacks     *
 *********************************/

function ldap_integration_login_validate($form_id, $form_values) {
  global $user;

  if (isset($form_values['name'])) {
    if (user_is_blocked($form_values['name'])) {
      // blocked in user administration
      form_set_error('login', t('The username %name has been blocked.', array('%name' => theme('placeholder', $form_values['name']))));
    }
    else if (drupal_is_denied('user', $form_values['name'])) {
      // denied by access controls
      form_set_error('login', t('The name %name is a reserved username.', array('%name' => theme('placeholder', $form_values['name']))));
    }
    else if ($form_values['pass']) {
      // === HACK STARTS ===
      // --- New code starts
      $user = _ldap_integration_code_changed_login_validate($form_values['name'], trim($form_values['pass']));
      // --- New code ends

      // --- Drupal's original code starts
      // $user = user_authenticate($form_values['name'], trim($form_values['pass']));
      // --- Drupal's original code ends
      // === HACK ENDS ===

      if (!$user->uid) {
        form_set_error('login', t('Sorry. Unrecognized username or password.') .' '. l(t('Have you forgotten your password?'), 'user/password'));
        watchdog('user', t('Login attempt failed for %user: %error.', array('%user' => theme('placeholder', $form_values['name']), '%error' => theme('placeholder', $error))));
      }
    }
  }
}

function _ldap_integration_code_changed_login_validate($name, $pass) {
  $user = null;

  if (_ldap_integration_is_ldap_login_only($name) == false) {
    // Authenticate locally only if not initially authenticated by LDAP, or if configured to do so
    $user = user_authenticate($name, $pass);
  }

  // If not successful, try LDAP authentication directly
  if (!$user->uid) {
    $user = _ldap_integration_ldap_login($name, $pass);
  }

  return $user;
}

function _ldap_integration_is_ldap_login_only($name) {
  return variable_get('ldap_login_process', LDAP_FIRST_LDAP) && db_num_rows(db_query("SELECT name FROM {users} WHERE locate('ldap_authentified',data) AND name='%s'",$name));
}

function _ldap_integration_ldap_login($login_string, $pass) {
  global $ldap;

  $user = null;

  // Strip name and server from ID:
  if ($server = strrchr($login_string, '@')) {
    $name = substr($login_string, 0, strlen($login_string) - strlen($server));
    $at = '@';
    $server = substr($server, 1);
  }
  else {
    $name = $login_string;
    $at = '';
    $server = '';
  }

  if (ldap_integration_auth($name, $pass, $server)) {
    $user = user_load(array('name' => "$name$at$server"));
    $tmp_user->name = "$name$at$server";
    if (!$user->uid) { // Register this new user.
      // Changes to this user_save():
      //   1. 'pass' => $pass . Obviously. What I wonder is how it could
      //      be otherwise. Really.
      //   2. 'mail' => value of LDAP_EMAIL_ATTRIBUTE in the LDAP directory
      //   3. 'init' => same. BTW: what's the use of this field?
      //   4. 'ldap_authentified' => TRUE . There is a need to mark
      //      people as externally authentified.
      $dn = _ldap_integration_login2dn("$name$at$server");
      $mail = $ldap->retrieveAttribute($dn, LDAP_EMAIL_ATTRIBUTE);
      $user = user_save('', array('name' => "$name$at$server", 'pass' => $pass, 'mail' => $mail, 'init' => $mail, 'status' => 1, "authname_ldap_integration" => "$name$at$server", 'roles' => array(_user_authenticated_id()), 'ldap_authentified' => TRUE, 'ldap_dn' => $dn));
      watchdog('user', t('New external user: %user using module %module.', array('%user' => theme('placeholder', $name .'@'. $server), '%module' => theme('placeholder', $module))), WATCHDOG_NOTICE, l(t('edit'), 'user/'. $user->uid .'/edit'));
    }
  }

  return $user;
}

/*********************************
 *          6. Themes            *
 *********************************/

function theme_ldap_integration_ldap_entry($attributes) {
  global $ldap_attributes;

  $attributes = $attributes ? $attributes : array();
  $output = "<dl>\n";
  foreach($attributes as $attribute => $value) {
    $attribute_title = $ldap_attributes[$attribute][2];
    $output .= "<dt><b>$attribute_title:</b></dt><dd>$value</dd>\n";
  }
  $output .= "</dl>\n";

  return $output;
}

/*********************************
 *        7. Debug utils         *
 *********************************/

function msg($string) {
  drupal_set_message("<pre style=\"border: 0; margin: 0; padding: 0;\">$string</pre>");
}

function msg_r($object) {
  ob_start();
  print_r($object);
  $output = ob_get_contents();
  ob_end_clean();
  msg($output);
}

?>